name: tabs_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  path: ^1.8.0
  path_provider: ^2.0.15
  intl: ^0.19.0
  smooth_corner: ^1.1.0
  flutter_animate: ^4.5.0
  uuid: ^4.5.1
  collection: ^1.19.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
